// <auto-generated />
using Isaac_SensorSettingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Isaac_SensorSettingService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201109122746_SettingModelUpdate")]
    partial class SettingModelUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Isaac_SensorSettingService.Models.SettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExpirationTime")
                        .HasColumnType("int");

                    b.Property<int>("Floor_id")
                        .HasColumnType("int");

                    b.Property<bool>("KeepData")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SensorSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
